explicitly depend on policy_fargate module
We frequently see terraform fail the first time with these sorts of
changes, with errors like:

    Error: MalformedPolicyDocumentException: Policy contains a statement with one or more invalid principals.

      on ../../../../../verify-infrastructure/terraform/modules/hub/kms.tf line 26, in resource "aws_kms_key" "hub_key":
      26: resource "aws_kms_key" "hub_key" {

even though it looks like the aws_kms_key.policy resource depends on
the module.policy_fargate module, via the
data.aws_iam_policy_document.policy data source.  Hopefully this will
fix it?  I can't say I'm super confident though, because these
dependencies really should be there already.

This also (sneakily) adds saml-soap-proxy-fargate to saml-engine's
nonProxyHosts setting.